- splitio/clients.py
- splitio/impressions.py
- splitio/redis_support.py
- splitio/splits.py
- splitio/splitters.py
- splitio/tests/test_redis_support.py
- splitio/tests/test_splits.py
- splitio/tests/test_splitters.py
- splitio/uwsgi.py
> add traffic allocation support

- splitio/splits.py
In Python 3 you cannot compare None with an integer. As a result, the localhost
implementation fails.
> Handle case of traffic_allocation being None

- splitio/segments.py
- splitio/splits.py
- splitio/tests/test_segments.py
- splitio/tests/test_splits.py
When an invalid response is received, instead of stopping fetcher threads, reschedule them with a timer
> [HOTFIX] - reschedule fetcher threads when connection fails

- splitio/splits.py
- splitio/tests/test_splits.py
Traffic allocation should be set to 100 if the value is not provided by the split.
Added a simple unit test to verify the behavior as well.
> Set traffic allocation to 100 by default

- setup.py
Fixes #166 
```sh
pip list
Package        Version    Location                  
-------------- ---------- --------------------------
asd            0          /home/sam/tmp/splitpy3test
certifi        2019.11.28 
cffi           1.13.2     
chardet        3.0.4      
docopt         0.6.2      
future         0.18.2     
idna           2.8        
mmh3cffi       0.1.4      
pip            18.1       
pycparser      2.19       
PyYAML         5.3        
requests       2.22.0     
setuptools     45.0.0     
splitio-client 8.1.7b1    
urllib3        1.25.7     
wheel          0.33.6     
```
> Fix installs on Python 3

- splitio/client/factory.py
- tests/client/test_factory.py
- tests/integration/test_client_e2e.py
The code change introduced in this PR ensures that a factory is ready when `block_until_ready` returns. Prior to this change, the value of `factory.ready` was not guaranteed to be `True` after `block_until_ready()` returns, which is counterintuitive. This behavior was due to the non-deterministic nature of Python thread scheduling.
This change can be tested by running the test suite. I simply removed the `time.sleep(1)` calls that enabled factory readiness assertions to pass before this change.
> Make block_until_ready() guarantee factory readiness

- splitio/recorder/recorder.py
- tests/recorder/test_recorder.py
> added async recorder classes

- setup.py
- splitio/client/client.py
- splitio/client/factory.py
- splitio/engine/telemetry.py
- splitio/models/telemetry.py
- splitio/push/manager.py
- splitio/push/parser.py
- splitio/push/processor.py
- splitio/push/workers.py
- splitio/storage/inmemmory.py
- splitio/sync/split.py
- splitio/sync/synchronizer.py
- splitio/sync/telemetry.py
- tests/engine/test_telemetry.py
- tests/integration/test_client_e2e.py
- tests/integration/test_streaming_e2e.py
- tests/models/test_telemetry_model.py
- tests/push/test_manager.py
- tests/push/test_parser.py
- tests/push/test_processor.py
- tests/push/test_split_worker.py
- tests/sync/test_telemetry.py
- tests/tasks/test_telemetry_sync.py
> added IFF feature to async branch

- splitio/api/auth.py
- splitio/api/commons.py
- splitio/spec.py
- splitio/sync/segment.py
- tests/api/test_auth.py
- tests/api/test_segments_api.py
- tests/api/test_splits_api.py
- tests/integration/test_streaming_e2e.py
- tests/sync/test_segments_synchronizer.py
- tests/tasks/test_segment_sync.py
> added spec query parameter

- splitio/api/client.py
- splitio/client/factory.py
- tests/api/test_httpclient.py
> refactored httpclient for kerberos auth

- splitio/api/client.py
- tests/api/test_httpclient.py
> Used four sessions per split host and reconnect when timing out

- splitio/engine/evaluator.py
- splitio/engine/impressions/impressions.py
- splitio/models/impressions.py
- splitio/models/splits.py
- splitio/recorder/recorder.py
- tests/engine/test_evaluator.py
- tests/engine/test_impressions.py
- tests/models/test_splits.py
> updated models and recorder

- splitio/models/grammar/condition.py
- splitio/models/grammar/matchers/__init__.py
- splitio/models/grammar/matchers/rule_based_segment.py
- splitio/models/rule_based_segments.py
- splitio/storage/__init__.py
- splitio/storage/inmemmory.py
- splitio/util/storage_helper.py
- tests/models/test_rule_based_segments.py
- tests/storage/test_inmemory_storage.py
- tests/sync/test_synchronizer.py
> Rbs models mem storage

- setup.py
- splitio/api/commons.py
- splitio/api/splits.py
- splitio/sync/split.py
- tests/api/test_segments_api.py
- tests/api/test_splits_api.py
- tests/sync/test_splits_synchronizer.py
> Update sync and api classes

- splitio/models/rule_based_segments.py
- splitio/storage/inmemmory.py
- splitio/storage/pluggable.py
- splitio/storage/redis.py
- splitio/sync/split.py
- tests/integration/__init__.py
- tests/storage/test_pluggable.py
- tests/storage/test_redis.py
- tests/sync/test_splits_synchronizer.py
- tests/sync/test_synchronizer.py
> updated redis, pluggable and localjson storages

- splitio/models/rule_based_segments.py
- splitio/models/telemetry.py
- splitio/push/parser.py
- splitio/push/processor.py
- splitio/push/workers.py
- splitio/spec.py
- splitio/storage/inmemmory.py
- splitio/storage/pluggable.py
- splitio/storage/redis.py
- splitio/sync/split.py
- tests/integration/__init__.py
- tests/push/test_split_worker.py
- tests/storage/test_pluggable.py
- tests/storage/test_redis.py
- tests/sync/test_splits_synchronizer.py
- tests/sync/test_synchronizer.py
> Updated SSE classes

- splitio/client/input_validator.py
- splitio/engine/impressions/strategies.py
- splitio/models/impressions.py
- tests/api/test_impressions_api.py
- tests/client/test_input_validator.py
- tests/engine/test_impressions.py
> Updated validation and model

- splitio/api/impressions.py
- splitio/client/client.py
- splitio/storage/pluggable.py
- splitio/storage/redis.py
- tests/api/test_impressions_api.py
- tests/client/test_client.py
- tests/client/test_input_validator.py
- tests/integration/test_client_e2e.py
- tests/integration/test_pluggable_integration.py
- tests/integration/test_redis_integration.py
- tests/recorder/test_recorder.py
- tests/storage/test_inmemory_storage.py
- tests/storage/test_pluggable.py
- tests/storage/test_redis.py
- tests/sync/test_impressions_synchronizer.py
- tests/tasks/test_impressions_sync.py
> Updated integration tests

- splitio/client/client.py
- splitio/client/input_validator.py
- tests/client/test_client.py
- tests/integration/test_client_e2e.py
> Replaced properties with evaluation options

- CHANGES.txt
- splitio/engine/impressions/adapters.py
> Added prevention for telemetry post if counters are empty
