splitio/python-client

- splitio/matchers.py
- splitio/splits.py
- splitio/tests/test_matchers.py
> String & set matchers

- Detailed-README.md
[SDKS-136: [Python] Documentation for Redis Sentinel](https://splitio.atlassian.net/browse/SDKS-136)
- Added documentation for cache.
> [SDKS-136]: [Python] Documentation for Redis Sentinel

- setup.py
*
* Bullet 1
* Bullet 2
*
* Bullet 1
* Bullet 2
> Updated new hash implementation package

- CHANGES.txt
updated changelog to reflect the breaking change of single queue
> Changelog updates

- splitio/api/auth.py
- splitio/api/client.py
- splitio/models/token.py
- tests/api/test_auth.py
- tests/models/test_token.py
> Auth-Client

- splitio/push/parser.py
- tests/push/test_parser.py
> added parser

- splitio/api/auth.py
- splitio/api/client.py
- splitio/api/events.py
- splitio/api/impressions.py
- splitio/api/segments.py
- splitio/api/splits.py
- splitio/api/telemetry.py
- splitio/client/client.py
- splitio/client/factory.py
- splitio/client/input_validator.py
- splitio/client/manager.py
- splitio/engine/evaluator.py
- splitio/models/grammar/matchers/numeric.py
- splitio/models/grammar/matchers/string.py
- splitio/storage/inmemmory.py
- splitio/storage/redis.py
- splitio/storage/uwsgi.py
- tests/client/test_client.py
- tests/client/test_input_validator.py
- tests/engine/test_evaluator.py
> refactored logger in apis

- splitio/client/factory.py
- splitio/sync/manager.py
- splitio/sync/synchronizer.py
- tests/client/test_factory.py
- tests/sync/test_synchronizer.py
> added shutdown method

- splitio/api/__init__.py
- splitio/api/auth.py
- splitio/api/commons.py
- splitio/api/events.py
- splitio/api/impressions.py
- splitio/api/segments.py
- splitio/api/splits.py
- splitio/api/telemetry.py
- splitio/client/input_validator.py
- splitio/push/splitsse.py
- splitio/sync/segment.py
- splitio/sync/split.py
- tests/api/test_auth.py
- tests/api/test_segments_api.py
- tests/api/test_splits_api.py
- tests/api/test_util.py
- tests/sync/test_segments_synchronizer.py
- tests/sync/test_splits_synchronizer.py
- tests/tasks/test_segment_sync.py
- tests/tasks/test_split_sync.py
> added cdn bypass segments

- .github/workflows/ci.yml
- .github/workflows/update-license-year.yml
- setup.py
> added gha for updating license

- .github/workflows/update-license-year.yml
> updated license

- CHANGES.txt
> Development rc

- CHANGES.txt
> Updated changes.txt

- splitio/client/factory.py
- splitio/engine/adapters.py
- splitio/engine/unique_keys_tracker.py
- splitio/sync/manager.py
- splitio/sync/synchronizer.py
- splitio/sync/unique_keys.py
- splitio/tasks/unique_keys_sync.py
Added None implementation for Redis
> Redis none

- splitio/api/telemetry.py
> Added v1 to telemetry URL

- splitio/client/factory.py
- splitio/engine/impressions/adapters.py
- splitio/sync/manager.py
- splitio/sync/synchronizer.py
- tests/client/test_factory.py
- tests/sync/test_manager.py
- tests/sync/test_synchronizer.py
> patch fix for timeout and redis imp count

- splitio/sync/segment.py
- splitio/sync/split.py
- splitio/sync/synchronizer.py
- tests/sync/test_segments_synchronizer.py
- tests/sync/test_splits_synchronizer.py
- tests/sync/test_synchronizer.py
> Added split and segment synching from json file to memory storage

- splitio/client/config.py
- splitio/client/factory.py
> Factory and config integration

- splitio/client/factory.py
- splitio/sync/split.py
- splitio/sync/synchronizer.py
- tests/integration/test_client_e2e.py
> added bur mechanism

- splitio/sync/segment.py
- splitio/sync/split.py
- splitio/sync/synchronizer.py
- splitio/sync/util.py
- tests/integration/test_client_e2e.py
- tests/sync/test_segments_synchronizer.py
- tests/sync/test_splits_synchronizer.py
> Json sanitize

- splitio/storage/pluggable.py
- tests/storage/test_pluggable.py
> Added split storage class and test

- splitio/storage/pluggable.py
- tests/storage/test_pluggable.py
> Added SegmentStorage class with tests

- splitio/storage/pluggable.py
- tests/storage/test_pluggable.py
> adding try/catch to split storage and cleanup

- splitio/storage/pluggable.py
- tests/storage/test_pluggable.py
> added impressions pluggable storage and tests

- splitio/storage/pluggable.py
- tests/storage/test_pluggable.py
> added EventStorage class with tests

- splitio/storage/pluggable.py
- tests/storage/test_pluggable.py
> Added expire_key method

- splitio/models/telemetry.py
- splitio/storage/pluggable.py
- splitio/storage/redis.py
- tests/storage/test_pluggable.py
- tests/storage/test_redis.py
> Added telemetry pluggable storage with tests

- splitio/client/input_validator.py
- tests/client/test_input_validator.py
> added validation and test

- splitio/client/config.py
- splitio/client/factory.py
- splitio/client/input_validator.py
- splitio/engine/impressions/__init__.py
- splitio/models/telemetry.py
- splitio/storage/pluggable.py
- splitio/storage/redis.py
- splitio/sync/synchronizer.py
- tests/client/test_config.py
- tests/client/test_factory.py
- tests/client/test_input_validator.py
- tests/storage/test_pluggable.py
- tests/storage/test_redis.py
- tests/sync/test_manager.py
> Factory integration for pluggable storage and tests

- tests/integration/test_client_e2e.py
- tests/integration/test_pluggable_integration.py
- tests/storage/test_pluggable.py
> Pluggable integration tests

- splitio/storage/pluggable.py
- tests/storage/test_pluggable.py
> Added expire to impressions and events keys

- splitio/client/config.py
- splitio/client/factory.py
- splitio/engine/impressions/__init__.py
- tests/client/test_config.py
- tests/integration/test_client_e2e.py
> Factory and test integration for pluggable optimized mode

- splitio/engine/impressions/adapters.py
- tests/integration/test_client_e2e.py
> Added support for NONE mode

- setup.py
> Fixed installing attrs lib error

- README.md
> DW - update readme

- doc/source/introduction.rst
> updated introduction.rst

- doc/source/introduction.rst
- splitio/client/client.py
> Dw client log func comments

- splitio/api/splits.py
> dw - updated log and comment in api.split

- splitio/engine/impressions/adapters.py
> update feature in engine.impressions.adapters

- splitio/push/splitworker.py
> dw - updated logs and comments in push.splitworker

- splitio/sync/split.py
> updated logs and comments in sync.split

- splitio/client/input_validator.py
> dw - updated feature in logs and func comments for input_validator

- splitio/sync/segment.py
> update comments in sync.segment

- splitio/client/factory.py
- tests/client/test_factory.py
> Rename api key in factory

- splitio/client/client.py
- splitio/client/input_validator.py
- tests/client/test_input_validator.py
> Update feature in client and input_validator

- splitio/engine/impressions/unique_keys_tracker.py
> updated vars in engine/impressions/unique_keys_tracker

- splitio/client/factory.py
> update vars factory

- splitio/client/client.py
- splitio/client/input_validator.py
- splitio/client/manager.py
- tests/client/test_input_validator.py
> updated vars and funcs in input_validator

- splitio/engine/evaluator.py
- tests/engine/test_evaluator.py
> update vars in engine.evaluator

- splitio/push/splitworker.py
> Updated variables in push.splitworker

- splitio/sync/telemetry.py
> update vars in sync.telemetry

- splitio/api/auth.py
- splitio/api/client.py
- splitio/api/events.py
- splitio/api/impressions.py
- splitio/api/segments.py
- splitio/api/splits.py
- splitio/api/telemetry.py
> updated apikey in splitio.api classes

- splitio/client/client.py
- splitio/client/config.py
- splitio/client/factory.py
- splitio/client/input_validator.py
- tests/client/test_input_validator.py
> updated apikey in splitio.client classes

- splitio/sync/split.py
- tests/sync/test_splits_synchronizer.py
> Fixed setting defaultTreatment to control when missing

- splitio/push/parser.py
- tests/push/test_parser.py
> Added support for FF to push.parser class

- splitio/push/splitworker.py
- tests/push/test_split_worker.py
> Added IFF support to split_worker class

- splitio/push/processor.py
- splitio/sync/split.py
- splitio/sync/synchronizer.py
- tests/push/test_processor.py
- tests/sync/test_splits_synchronizer.py
> Added integration to sync support

- splitio/push/parser.py
- splitio/push/splitworker.py
- tests/client/test_localhost.py
- tests/integration/test_client_e2e.py
- tests/integration/test_streaming_e2e.py
- tests/push/test_manager.py
- tests/push/test_split_worker.py
> Added e2e tests

- splitio/push/parser.py
- splitio/push/splitworker.py
- tests/integration/test_streaming_e2e.py
> Added discard split event if change number is null

- splitio/api/__init__.py
- splitio/api/auth.py
- splitio/api/client.py
- splitio/api/commons.py
- splitio/api/events.py
- splitio/api/impressions.py
- splitio/api/segments.py
- splitio/api/splits.py
- splitio/api/telemetry.py
- splitio/push/splitsse.py
- tests/api/test_auth.py
- tests/api/test_events.py
- tests/api/test_httpclient.py
- tests/api/test_impressions_api.py
- tests/api/test_segments_api.py
- tests/api/test_splits_api.py
- tests/api/test_util.py
- tests/push/test_manager.py
- tests/sync/test_events_synchronizer.py
- tests/sync/test_impressions_count_synchronizer.py
- tests/sync/test_impressions_synchronizer.py
- tests/tasks/test_events_sync.py
- tests/tasks/test_impressions_sync.py
- tests/tasks/test_unique_keys_sync.py
> Added async to latest main branch

- splitio/push/splitworker.py
- tests/push/test_split_worker.py
> added handling archived split

- splitio/push/manager.py
- splitio/push/sse.py
- tests/push/test_sse.py
> Async sse class

- splitio/push/processor.py
- splitio/push/workers.py
- tests/push/test_processor.py
> Added processor async class

- splitio/storage/adapters/redis.py
- tests/storage/adapters/test_redis_adapter.py
> added async redis adapter

- splitio/engine/telemetry.py
- splitio/models/telemetry.py
- splitio/push/manager.py
- splitio/push/processor.py
- splitio/push/segmentworker.py
- splitio/push/splitworker.py
- splitio/storage/inmemmory.py
- splitio/sync/telemetry.py
- tests/engine/test_telemetry.py
- tests/models/test_telemetry_model.py
- tests/push/test_manager.py
- tests/push/test_processor.py
- tests/push/test_split_worker.py
- tests/sync/test_telemetry.py
> Added telemetry to iff update

- splitio/storage/adapters/cache_trait.py
- splitio/storage/redis.py
- tests/storage/adapters/test_cache_trait.py
- tests/storage/test_redis.py
> Added async Redis split storage

- splitio/storage/redis.py
- tests/storage/test_redis.py
> Added redis impressions async storage

- splitio/storage/redis.py
- tests/storage/test_redis.py
> added telemetry redis storage async

- setup.cfg
- splitio/push/sse.py
- tests/push/test_sse.py
> Add refactored SSEClient class

- splitio/optional/loaders.py
- splitio/push/splitsse.py
- tests/push/test_splitsse.py
> Refactored SplitSSEClientAsync

- splitio/storage/redis.py
- tests/push/test_processor.py
- tests/storage/test_redis.py
> added redis event async storage class

- splitio/storage/inmemmory.py
- tests/storage/test_inmemory_storage.py
> created inmemory split storage async

- splitio/sync/unique_keys.py
- tests/sync/test_unique_keys_sync.py
> added sync unique keys tracker class

- splitio/engine/impressions/unique_keys_tracker.py
- tests/engine/test_unique_keys_tracker.py
> Async engine unique keys tracker

- splitio/storage/inmemmory.py
- tests/storage/test_inmemory_storage.py
> added memory segment storage async class

- splitio/storage/inmemmory.py
- tests/storage/test_inmemory_storage.py
> added memory imps async storage

- splitio/storage/inmemmory.py
- tests/storage/test_inmemory_storage.py
> added memory async event storage

- splitio/storage/inmemmory.py
- tests/storage/test_inmemory_storage.py
> Added telemetry memory storage async class

- splitio/engine/telemetry.py
- tests/engine/test_telemetry.py
> added async engine telemetry classes

- splitio/engine/impressions/adapters.py
- tests/engine/test_send_adapters.py
> Added engine.impressions.adapters async classes

- splitio/models/telemetry.py
- tests/models/test_telemetry_model.py
> added telemetr async model

- splitio/sync/split.py
- tests/sync/test_splits_synchronizer.py
> added sync split synchronizer async class

- splitio/sync/impression.py
- tests/sync/test_impressions_count_synchronizer.py
- tests/sync/test_impressions_synchronizer.py
> added impressions and impressions count sync classes

- splitio/sync/event.py
- tests/sync/test_events_synchronizer.py
> Added sync event async class

- splitio/engine/evaluator.py
- tests/engine/test_evaluator.py
> Updated engine evaluator class

- splitio/models/grammar/matchers/keys.py
- splitio/models/grammar/matchers/misc.py
- tests/models/grammar/test_matchers.py
> updated dependency and segment matchers

- splitio/tasks/segment_sync.py
- tests/tasks/test_segment_sync.py
> added tasks.sync segment async class

- splitio/tasks/split_sync.py
- tests/tasks/test_split_sync.py
> added tasks.sync split async class

- splitio/tasks/impressions_sync.py
- tests/tasks/test_impressions_sync.py
> added tasks.sync imps async classes

- splitio/tasks/events_sync.py
- tests/tasks/test_events_sync.py
> added tasks.event_sync async class

- splitio/sync/segment.py
- tests/sync/test_segments_synchronizer.py
> added sync segment local class

- splitio/optional/loaders.py
- splitio/sync/split.py
- tests/sync/test_splits_synchronizer.py
> added sync.split local async class

- splitio/engine/telemetry.py
- splitio/sync/telemetry.py
- tests/sync/test_telemetry.py
> added sync.telemetry async classes with a fix in engine.telemetry

- splitio/api/auth.py
- splitio/api/client.py
- splitio/api/commons.py
- splitio/api/events.py
- splitio/api/impressions.py
- splitio/api/segments.py
- splitio/api/splits.py
- splitio/api/telemetry.py
- tests/api/test_auth.py
- tests/api/test_events.py
- tests/api/test_httpclient.py
- tests/api/test_impressions_api.py
- tests/api/test_segments_api.py
- tests/api/test_splits_api.py
- tests/api/test_telemetry_api.py
- tests/api/test_util.py
> moved telemetry call to api.client for async

- splitio/sync/segment.py
- splitio/tasks/util/workerpool.py
- tests/sync/test_segments_synchronizer.py
- tests/tasks/util/test_workerpool.py
> Added workerpool and sync.segment async classes

- splitio/sync/manager.py
- tests/sync/test_manager.py
> added sync redis manager async class

- splitio/sync/synchronizer.py
- tests/sync/test_synchronizer.py
> added sync localhost synchronizer async class

- splitio/client/config.py
- splitio/client/input_validator.py
- tests/client/test_config.py
> updated client.config and client.input_validator

- splitio/models/splits.py
- tests/models/test_splits.py
> Update split model

- splitio/sync/synchronizer.py
- tests/sync/test_synchronizer.py
> added redis syncrhonizer async class

- splitio/sync/manager.py
- tests/sync/test_manager.py
> added sync manager

- splitio/sync/segment.py
- splitio/sync/synchronizer.py
- splitio/tasks/unique_keys_sync.py
- tests/sync/test_synchronizer.py
> Added sync.synchronizer async class, updated tasks.unique_keys classes

- splitio/optional/loaders.py
- splitio/push/manager.py
- splitio/sync/manager.py
- splitio/sync/synchronizer.py
- splitio/tasks/events_sync.py
- splitio/tasks/impressions_sync.py
- splitio/tasks/segment_sync.py
- splitio/tasks/split_sync.py
- splitio/tasks/telemetry_sync.py
- splitio/tasks/unique_keys_sync.py
- splitio/tasks/util/asynctask.py
- tests/sync/test_manager.py
- tests/sync/test_synchronizer.py
- tests/tasks/test_telemetry_sync.py
> several code polishing

- splitio/engine/telemetry.py
- tests/engine/test_telemetry.py
> updated engine.telemetry class

- splitio/models/splits.py
- splitio/storage/inmemmory.py
- tests/storage/test_inmemory_storage.py
> updated storage inmemory split storage

- splitio/client/config.py
- tests/client/test_config.py
> added flag set validations to config

- splitio/api/commons.py
- splitio/api/splits.py
- tests/api/test_splits_api.py
> updated api.split and api.commons

- splitio/push/splitworker.py
- splitio/sync/split.py
- splitio/util/storage_helper.py
- tests/push/test_split_worker.py
- tests/util/test_storage_helper.py
> Updated push.splitworker and sync.split

- splitio/client/client.py
- splitio/client/factory.py
- splitio/storage/pluggable.py
- tests/storage/test_pluggable.py
> updted storage.pluggable class

- splitio/client/config.py
- splitio/client/factory.py
- splitio/models/telemetry.py
- tests/models/test_telemetry_model.py
> Added flagset support to factory

- splitio/client/client.py
- splitio/client/factory.py
- splitio/client/input_validator.py
- splitio/engine/telemetry.py
- splitio/models/telemetry.py
- splitio/storage/__init__.py
- splitio/storage/inmemmory.py
- splitio/storage/pluggable.py
- splitio/storage/redis.py
- splitio/sync/split.py
- splitio/util/storage_helper.py
- tests/client/test_factory.py
- tests/client/test_input_validator.py
- tests/engine/test_telemetry.py
- tests/models/test_telemetry_model.py
- tests/storage/test_flag_sets.py
- tests/storage/test_inmemory_storage.py
- tests/storage/test_pluggable.py
- tests/storage/test_redis.py
- tests/sync/test_splits_synchronizer.py
- tests/sync/test_synchronizer.py
- tests/tasks/test_split_sync.py
> Added flagsets total and invalid count for telemetry config

- splitio/client/client.py
- splitio/models/splits.py
- tests/client/test_client.py
- tests/models/test_splits.py
> added warning when not ready

- splitio/storage/inmemmory.py
> fixed exception when new flagset detected

- splitio/storage/adapters/redis.py
- tests/storage/adapters/test_redis_adapter.py
> added sentinel async

- splitio/api/telemetry.py
- splitio/storage/redis.py
- tests/storage/test_redis.py
> Updated redis storage to reflect flagset filter

- splitio/api/telemetry.py
- splitio/storage/redis.py
- tests/storage/test_redis.py
Reverts splitio/python-client#483
> Revert "Updated redis storage to reflect flagset filter"

- CHANGES.txt
- splitio/api/telemetry.py
- splitio/client/config.py
- tests/client/test_config.py
> Flagset config fix

- splitio/api/client.py
- splitio/client/client.py
- splitio/client/input_validator.py
- splitio/client/manager.py
- splitio/engine/evaluator.py
- splitio/models/grammar/matchers/keys.py
- splitio/models/grammar/matchers/misc.py
- splitio/optional/loaders.py
- splitio/push/sse.py
- splitio/storage/pluggable.py
- splitio/tasks/util/workerpool.py
- tests/api/test_httpclient.py
- tests/client/test_client.py
- tests/client/test_factory.py
- tests/client/test_input_validator.py
- tests/engine/test_evaluator.py
- tests/integration/files/splitChanges.json
- tests/integration/files/split_changes.json
- tests/integration/test_client_e2e.py
- tests/integration/test_streaming_e2e.py
- tests/models/grammar/test_matchers.py
- tests/models/test_telemetry_model.py
- tests/storage/test_inmemory_storage.py
- tests/storage/test_pluggable.py
> Moved fetching from storage to evaluator

- splitio/client/listener.py
- splitio/engine/evaluator.py
> Fixed exception when matcher ALL_KEYS does not exist

- splitio/engine/telemetry.py
> updated engine telemetry

- splitio/storage/__init__.py
- splitio/storage/inmemmory.py
- splitio/util/storage_helper.py
- tests/storage/test_flag_sets.py
- tests/storage/test_inmemory_storage.py
> Async flagset storage memory

- splitio/models/splits.py
- splitio/models/telemetry.py
- tests/models/test_splits.py
- tests/models/test_telemetry_model.py
> updated split and telemetry models

- splitio/api/commons.py
- splitio/api/splits.py
- splitio/api/telemetry.py
- tests/api/test_splits_api.py
- tests/api/test_telemetry_api.py
> updated api commons, split and telemetry classes

- splitio/push/workers.py
- tests/push/test_split_worker.py
> updated push splitworker

- splitio/api/__init__.py
- splitio/push/workers.py
- splitio/sync/manager.py
- splitio/sync/split.py
- splitio/sync/synchronizer.py
- splitio/tasks/util/asynctask.py
- tests/sync/test_splits_synchronizer.py
- tests/sync/test_synchronizer.py
- tests/sync/test_telemetry.py
- tests/tasks/test_split_sync.py
> updated sync.split, sync.synchronizer and tasks.util.asynctask classes

- splitio/storage/adapters/redis.py
- splitio/storage/pluggable.py
- splitio/storage/redis.py
- tests/integration/test_pluggable_integration.py
- tests/storage/test_pluggable.py
- tests/storage/test_redis.py
> updated adapter.redis, storage.redis and storage.pluggable

- CHANGES.txt
> updated date in changes

- splitio/models/grammar/matchers/__init__.py
- splitio/models/grammar/matchers/semver.py
- tests/models/grammar/test_matchers.py
> added greater or equal to semver matcher

- splitio/models/grammar/matchers/__init__.py
- splitio/models/grammar/matchers/semver.py
- tests/models/grammar/test_matchers.py
> added less than or equal semver matcher

- setup.cfg
- setup.py
- splitio/models/grammar/matchers/__init__.py
- splitio/models/grammar/matchers/semver.py
- tests/models/grammar/test_matchers.py
> added semver between matcher

- splitio/models/splits.py
> removed unnecesary pass

- splitio/models/grammar/condition.py
- splitio/models/grammar/matchers/semver.py
- splitio/models/grammar/matchers/utils/utils.py
- splitio/models/splits.py
- splitio/sync/segment.py
- tests/models/grammar/test_matchers.py
- tests/models/grammar/test_semver.py
> made some cleanup in code for semver

- .github/workflows/ci.yml
- setup.py
> dropping support to python 3.6 EOL

- setup.cfg
- setup.py
- splitio/client/client.py
- splitio/client/factory.py
- splitio/push/manager.py
- splitio/push/splitsse.py
- splitio/push/sse.py
- splitio/push/status_tracker.py
- splitio/sync/manager.py
- splitio/sync/synchronizer.py
- splitio/tasks/util/asynctask.py
- splitio/tasks/util/workerpool.py
- tests/client/test_factory.py
- tests/integration/test_client_e2e.py
- tests/integration/test_streaming_e2e.py
- tests/push/test_sse.py
> added SSE total and socket read timeouts

- CHANGES.txt
- setup.cfg
- splitio/storage/adapters/redis.py
- tests/integration/test_streaming_e2e.py
> Async release 10.0.0

- splitio/engine/evaluator.py
- splitio/engine/impressions/impressions.py
- tests/engine/test_evaluator.py
- tests/engine/test_impressions.py
> updated impressions and evaluator classes

- splitio/engine/evaluator.py
- splitio/models/rule_based_segments.py
- splitio/storage/inmemmory.py
- splitio/util/storage_helper.py
- tests/engine/test_evaluator.py
- tests/models/test_rule_based_segments.py
- tests/storage/test_pluggable.py
- tests/util/test_storage_helper.py
> updated storage helper and evaluator

- splitio/client/factory.py
- splitio/models/grammar/matchers/rule_based_segment.py
- splitio/models/rule_based_segments.py
- splitio/storage/inmemmory.py
- splitio/sync/segment.py
- splitio/sync/split.py
- splitio/util/storage_helper.py
- tests/engine/files/rule_base_segments2.json
- tests/engine/test_evaluator.py
- tests/sync/test_segments_synchronizer.py
- tests/sync/test_synchronizer.py
- tests/tasks/test_segment_sync.py
- tests/util/test_storage_helper.py
> Rbs fix segment initial fetch

- splitio/models/grammar/matchers/prerequisites.py
- tests/models/grammar/files/splits_prereq.json
- tests/models/grammar/test_matchers.py
> Added matcher

- splitio/client/client.py
- tests/client/test_client.py
> Fme 4288 imp prop client
